### PR TITLE
DOC-8132-C6 -- Move C code_snippets module in to clang

### PR DESCRIPTION
**Pull request by ibsoln**
1. Move the code module from JB's initial commit into modules/clang/ examples/code_snippets; this also removes the preexisting debris from examples/
2. Add the include:: for  the getting-started code into the verify/build page
https://issues.couchbase.com/browse/DOC-8132
3. Set {snippets} attribute for new module

### CODE REVIEW

**Comment by ibsoln** [comment]
Hi @borrrden I've pulled your feature branch into the main docs module in the PR. If you are ok with this then please I'll merge it.
You can work directly in this new location or continue to work in your feature branch; either way I can pull in any changes as-and-when.

**Comment by borrrden** [comment]
I'd prefer not to name this `clang` as it is confusing.  It sounds like it is meant for the `clang` compiler (https://clang.llvm.org/).  What is the issue with using `c` ?

**Comment by ibsoln** [comment]
> I'd prefer not to name this `clang` as it is confusing. It sounds like it is meant for the `clang` compiler (https://clang.llvm.org/). What is the issue with using `c` ?

No problem @borrrden . I can rename.

**Comment by ibsoln** [comment]
I've merged that in and will push another PR to rename `clang` to `c`

**Pull request merged**
