### PR TITLE
API references page attribute

### PR DESCRIPTION
**Pull request by jamesnocentini**
add `url-api-references` page attribute and replace throughout page

### CODE REVIEW

**Comment by simon-dew** [comment]
Out of interest, why do these docs contain links to the compiled html pages, rather than xrefs to the AsciiDoc source?

**Comment by jamesnocentini** [comment]
Glad you asked. API refs (for [swift](https://docs.couchbase.com/mobile/2.5.0/couchbase-lite-swift/) for example) are generated with tools specific to each platform (Jazzy for Swift/ObjC, Sandcastle for C# and JavaDoc for Java). We could maintain an API ref in AsciiDoc itself, but, developers tend to prefer the format generated by the tools on the platform of their choice (e.g JavaDoc is very popular within the Java community). It's also much easier for us to generate API refs from a command line than to ensure correctness by hand (probably the biggest reason to justify that choice).

**Comment by simon-dew** [comment]
Ah, understood!

**Review by simon-dew — APPROVED** [review]
Approved, when [conflicts](https://github.com/couchbase/docs-couchbase-lite/pull/96/conflicts) are resolved

**Pull request merged**
