### PR TITLE
apply sentence per line to prose (aka ventilated prose) (master)

### PR DESCRIPTION
**Pull request by mojavelinux**
I applied sentence per line formatting to all the prose, which includes paragraphs, list items, and table cells. If this looks good to you, I'll do the same for the other branches as well.

### CODE REVIEW

**Comment by jamiltz** [comment]
Looks good. Yes that'd be great as this isn't a change that can easily be cherry picked.

**Comment by mojavelinux** [comment]
Excellent. I'll submit PRs for the other branches as well.

**Comment by mojavelinux** [comment]
Sent!

**Comment by jamiltz** [comment]
Thanks!

**Pull request merged**
