### PR TITLE
DOC-5813-Query-example-for-Like-op

### PR DESCRIPTION
**Pull request by ibsoln**
https://issues.couchbase.com/browse/DOC-5813
https://issues.couchbase.com/browse/DOC-5915

Code review required @bmeike

### CODE REVIEW

**Comment by ibsoln** [comment]
For review by @bmeike per https://issues.couchbase.com/browse/DOC-5915

**Review by bmeike — APPROVED** [review]
Did you run this?  Does it work?  If not, please create a ticket for me to do so...

**Comment by ibsoln** [comment]
Sorry, Blake. Forgot to get back to you on this.

I ran it on  a getting-started DB I setup. And yes it worked. The Db stores docs with a ‘language’ field set to “Java”.

query = QueryBuilder
        .select(
                SelectResult.expression(Meta.id),
                SelectResult.property("language"),
                SelectResult.property("version"))
        .from(DataSource.database(database))
        .where(Expression.property("type").equalTo(Expression.string("SDK"))
                .and(Function.lower(Expression.property("language")).like(Expression.string("java"))));


The query finds them all when using function.lower and searching for ‘java’ and none when using function.lower and searching for “Java”

/Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=64334:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Users/ianbridge/Documents/couchbase/cblDev/cblDev270/intelliSrc/out/production/intelliSrc:/Users/ianbridge/Documents/couchbase/cblDev/cblDev270/intelliSrc/libs1/couchbase-lite-java-ee-2.7.0-DB001.jar:/Users/ianbridge/Documents/couchbase/cblDev/cblDev270/intelliSrc/libs1/json-20180813.jar:/Users/ianbridge/Documents/couchbase/cblDev/cblDev270/intelliSrc/libs1/okhttp-3.9.1.jar:/Users/ianbridge/Documents/couchbase/cblDev/cblDev270/intelliSrc/libs1/okio-1.13.0.jar com.ibsoln.code.ibjavap1.Main
W/CouchbaseLite/DATABASE:Database.log.getFile().getConfig() is null, meaning file logging is disabled.  Log files required for product support are not being generated.
Document ID :: 9e4904d5-784e-4c2c-9a41-509549e0ec8e
Learning ObjC
Number of rows ::  5
Finds all = 'java'
0... 61c8e8fe-73b3-45a8-8fc4-874bf456ece1 ... language Java
1... 1d96cc35-6fa7-48d7-9390-435e8de26ed9 ... language Java
2... 311e6164-1cbb-428c-a3cb-a126c1e34e97 ... language Java
Completed - pattern matching
Finds none looking for = 'Java'
Completed - pattern matching

Process finished with exit code 0

**Comment by bmeike** [comment]
Awesome, Ian!  Thanks a bunch!

**Pull request merged**
