### PR TITLE
DOC-5409 - application events on Android

### PR DESCRIPTION
**Pull request by jamesnocentini**
https://issues.couchbase.com/browse/DOC-5409

### CODE REVIEW

**Comment by bmeike** [comment]
Whoah!  Is this still a thing?  Huge apologies for missing it for so long.
There are no such things as "background" or "foreground" events in Android.  There is also no such thing as an Android app "being in background"
If you can tell me what point you are trying to get across, here I might be able to help you word it....

**Review by bmeike — DISMISSED** [review]
This new section is really neither correct nor useful.  We should try to re-word it.

**Comment by jamesnocentini** [comment]
@bmeike We're trying to explain how one would go about stopping/starting the replicator when the user leaves the app/returns to it, with the current version of Couchbase Lite. How would you recommend that we do it?

**Comment by bmeike** [comment]
Got it.

There really isn’t any equivalent, for Android.  The user is either looking at the app, or she is not.  That is the only programmatically available information.

-blake

**Comment by bmeike** [comment]
It is my opinion that that note only perpetuates the misunderstanding of anyone that thinks it is useful.  Acting on the advice that it gives will result in code that is worse, not better.  I would remove it.

**Comment by ibsoln** [comment]
@rajagp If you're ok with @bmeike comments then I'll remove this change.

**Comment by ibsoln** [comment]
Thanks @bmeike I’ll go with that (https://issues.couchbase.com/browse/DOC-5409) it provides both the warning and a basic avoidance use-case. Hopefully, @rajagp you agree? 
See commit 551beaf on PR#112

**Review by rajagp — APPROVED** [review]

**Review by bmeike — APPROVED** [review]
Great!

**Pull request merged**
