### PR TITLE
clean link:, URL, and image references (release/1.4)

### PR DESCRIPTION
**Pull request by graphitefriction**
- add attributes for API and issue tracker URLs
- add GIF images to images directory
- convert link: to same-page xrefs
- convert unordered labeled lists to description lists

### CODE REVIEW

**Comment by graphitefriction** [comment]
@jamiltz This PR will probably have some conflicts with PR #46. After you merge PR #46, I'll rebase and resubmit.

**Comment by jamiltz** [comment]
@graphitefriction Ok. Merged PR https://github.com/couchbaselabs/docs-couchbase-lite/pull/46.

**Comment by graphitefriction** [comment]
@jamiltz Rebased...for now :wink:

**Comment by mojavelinux** [comment]
@jamiltz please take this one before #54. I'll rebase as necessary, or just apply those changes manually.

**Pull request merged**
