### PR TITLE
Pr/java 3.2.beta.2

### PR DESCRIPTION
**Pull request by bmeike**
Updates for the beta 2 release.

Please note that the example code for Java is *EXACTLY* where it should be, in the Java module.

### CODE REVIEW

**Comment by bmeike** [comment]
can't rebase this on 3.2 for some reason

**Comment by bmeike** [comment]
Pilot error.  Fixed.

**Review by ElliotFrancisHunter — APPROVED** [review]
LGTM! 👍🏼 holding off on merging until ready to launch Beta 2 on Java Desktop. Otherwise we could end up confusing existing Beta 1 users

**Comment by ElliotFrancisHunter** [comment]
Holding off on merge until beta 2 is ready for release.

**Pull request merged**
