### PR TITLE
DOC-5051

### PR DESCRIPTION
**Pull request by jamesnocentini**
https://issues.couchbase.com/browse/DOC-5051

### CODE REVIEW

**Comment by jamesnocentini** [comment]
Screenshot: 
image

**Comment by jamesnocentini** [comment]
@rajagp If I recall correctly, CBL and CBS SDKs are aligned on the usage of interface stability terms so suggesting to reuse the same.

@RichardSmedley you already had a partial for this section of SDK docs so I went ahead and used that. It's the first time CBL docs pull content from the sdk repo so it would be good to get your thoughts on this approach.

**Comment by rajagp** [comment]
@jamiltz  Yes, we are aligned on definition. Also, is there a place on server docs where term "Developer Preview" is defined (asking in context of predictive query stuff)

**Review by RichardSmedley — APPROVED** [review]
Interface stability partial import LGTM :+1:

**Comment by jamesnocentini** [comment]
@rajagp After checking with the wider doc team it appears there isn't a page defining "Developer Preview" on docs.couchbase.com yet. Can discuss on Slack how we want to handle that for 2.5.

**Review by rajagp — APPROVED** [review]

**Pull request merged**
