### PR TITLE
CBL-6019: Refresh .NET vector search code snippets

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by borrrden** [comment]
The C# validation depends on #880

**Comment by ElliotFrancisHunter** [comment]
@borrrden I've merged in #880 - Please resolve merge conflicts :) for some reason the validate build seems to still be failing for the remaining c# builds

**Comment by borrrden** [comment]
They will all fail until they are rebased on top of the 880 commit

**Comment by borrrden** [comment]
rebased

**Review by ElliotFrancisHunter — APPROVED** [review]

**Pull request merged**
