### PR TITLE
Revert "DOC-5578 - restore Android EE internal maven instructions"

### PR DESCRIPTION
**Pull request by jamesnocentini**
This reverts commit 394cdb8031c19dfb45165880d899a21b0bd776cf.

### CODE REVIEW

**Comment by jamesnocentini** [comment]
@bmeike can this be merged? are we sure it works without it now?

**Comment by bmeike** [comment]
I don't understand how we are ever going to get people to stop using our unsupported, internal server if we keep advertising it.
The short answer to your question is that it will break.  Anyone who is using that URL will break, when we stop supporting it (if that ever happens.  I despair, but that's another story).  In order to break the cycle, it seems to me that we ought to stop advertising it.
Hey!  Just me.
I think @rajagp  has a plan.  I think the best thing to do is to check in with her.

**Comment by jamesnocentini** [comment]
> In order to break the cycle, it seems to me that we ought to stop advertising it.

Sure, as long as it works without it. Otherwise people won’t know how to install EE which is basically like saying “here’s EE, oh and by the way you can’t use it because some instructions are gone”. I’ll merge this PR once we are certain that EE can be installed without the internal maven url.

**Review by bmeike — COMMENTED** [review]
I've stated my objections.  We should not advertise our flaky as hell internal maven server.

**Comment by jamesnocentini** [comment]
> I've stated my objections. We should not advertise our flaky as hell internal maven server.

@bmeike Noted. Is it currently possible to install EE w/o the internal maven server?

**Review by ibsoln — APPROVED** [review]

**Pull request merged**
