### PR TITLE
Doc 10249 documents page (pre-requisites WIP)

### PR DESCRIPTION
**Pull request by osfameron**
WIP on documents page.
This is all just cleanup so far, including the big `[source]` fix, and of course callouts.

(affects a few other pages other than document, because of having to make a change to the query-resultset partial).

NB: will need to have `base` set to our feature/release branch rather than release/3.0.

### CODE REVIEW

**Review by RayOffiah — APPROVED** [review]
Nice job. 👍🏾

Once it's merged into release, can you rebase 

origin/DOC-10385-Docs-for-Mobile-Scopes-and-Collections

on top of it?

**Comment by RayOffiah** [comment]
Oh hang on; you're not done yet!

**Comment by osfameron** [comment]
Well, the options are:

1. Merge this into Release (as it's preparatory refactoring) and rebase the feature branch onto it. Then create a *new* PR for the actual ticket work.
2. Merge this (prep *and* ticket work) into the Feature branch once complete.

Will hold off a little to see if can discuss those with you when you're back, or I can make a call if needed.

**Comment by RayOffiah** [comment]
I'm rather keen on option 1: gets the fixes into the existing code base so we can take advantage of them in changes that are not related to the scopes and collections work.

**Comment by osfameron** [comment]
OK, makes sense, will merge into main, and merge into the release branch then 👍

**Pull request merged**
