### PR TITLE
Doc 5710 apply beta2 change

### PR DESCRIPTION
**Pull request by ibsoln**

### CODE REVIEW

**Comment by ibsoln** [comment]
Please review/mark approved to facilitate merge @couchbase/documentation-writers

**Comment by eric-schneider** [comment]
@ibsoln Can you please provide a review build via GitHub Pages, etc? It will be helpful to see the generated pages and to assist with testing xrefs.

**Comment by ibsoln** [comment]
> @ibsoln Can you please provide a review build via GitHub Pages, etc? It will be helpful to see the generated pages and to assist with testing xrefs.

@eric-schneider Certainly. I'm just completing the remaining changes (tomcat and embedded-tomcat deployment) and will publish to github when available.

**Comment by ibsoln** [comment]
Java getting started pages etc can be seen at https://ibsoln.github.io/myStaging/couchbase-lite/2.7/java-jvm.html#get-started. The 5 PR pushed here but not merged may not be included in the build

**Comment by ibsoln** [comment]
Withdrawing to resubmit with additional changes.

**Pull request closed without merging**
