### PR TITLE
Add examples for ObjC

### PR DESCRIPTION
**Pull request by jayahariv**
* add example for push and pull filters. 
* fix some build errors.

### CODE REVIEW

**Review by jamesnocentini — CHANGES_REQUESTED** [review]
The push and pull filters have a slightly different callback body (one to filter on the type prop, the other to filter out deletions).

See https://github.com/couchbase/docs-couchbase-lite/blob/doc-4451/modules/ROOT/examples/swift/code-snippets/SampleCodeTest.swift#L601-L630

**Comment by jayahariv** [comment]
ideal flag checking for Swift will be, `flags.contains(.deleted)` not `flags.rawValue == deleted.rawValue`. Since the flags are saved in a OptionSet, and can have value of multiple flag values. 

[issue loc](https://github.com/couchbase/docs-couchbase-lite/blob/doc-4451/modules/ROOT/examples/swift/code-snippets/SampleCodeTest.swift#L626)
[example unit tests](https://github.com/couchbase/couchbase-lite-ios/blob/master/Swift/Tests/ReplicatorTest.swift#L221)

**Comment by jamesnocentini** [comment]
👍

**Review by jamesnocentini — APPROVED** [review]

**Comment by jamesnocentini** [comment]
Re deleted flag checking, I've updated the swift if statement ([dc8be42](https://github.com/couchbase/docs-couchbase-lite/commit/dc8be424cbc6ad70fb08470d3df040beb6ee7608)). Hopefully that is correct.

**Pull request merged**
