### PR TITLE
DOC-5994 - supportability android

### PR DESCRIPTION
**Pull request by ibsoln**
https://issues.couchbase.com/browse/DOC-5994

### CODE REVIEW

**Review by RichardSmedley — CHANGES_REQUESTED** [review]
Maybe change
>> We do not test or guarantee the support of uncertified versions such versions of Android built from source.
to 
>> We do not test or provide support for uncertified versions of Android, such as versions built from source.

**Comment by bmeike** [comment]
I don't think that is correct.  We *will* attempt to support them.  We just don't guarantee that we can.  In particular, when a paying customer puts our code on their custom tablet, we definitely will support it.

**Comment by RichardSmedley** [comment]
> I don't think that is correct. We _will_ attempt to support them. We just don't guarantee that we can. In particular, when a paying customer puts our code on their custom tablet, we definitely will support it.

Ah, in that case I suggest:
_We do not test against, nor guarantee to be able to support, uncertified Android versions such as versions built from source._

**Comment by bmeike** [comment]
Lovely!  Perhaps "... nor guarantee support for ..."

**Review by RichardSmedley — APPROVED** [review]
Thanks @ibsoln 
LGTM :+1:

**Review by bmeike — APPROVED** [review]

**Pull request merged**
